/**
 * @conveaux/contract-id
 *
 * Abstract ID generation contract with pluggable implementations.
 * Supports random IDs, time-ordered IDs, and W3C trace context IDs.
 *
 * Design Philosophy:
 * - Abstract categories over specific formats
 * - Runtime injection of implementations (uuid, nanoid, ULID, etc.)
 * - Sensible defaults when no injection provided
 * - W3C trace/span remains fixed format (OTel compliance)
 */

// =============================================================================
// Branded Types (compile-time safety)
// =============================================================================

/**
 * A cryptographically random ID with no time component.
 *
 * Use cases:
 * - Session tokens
 * - Nonces
 * - Cache keys
 * - Correlation IDs
 *
 * Properties:
 * - Maximum entropy per byte
 * - No ordering guarantees
 * - Unpredictable (crypto-secure)
 *
 * Branded type prevents accidental misuse at compile time.
 *
 * @example
 * ```typescript
 * const sessionId: RandomId = generator.randomId();
 * ```
 */
export type RandomId = string & { readonly __brand: 'RandomId' };

/**
 * A time-ordered ID with embedded timestamp.
 *
 * Use cases:
 * - Database primary keys
 * - Event IDs
 * - Audit logs
 * - Message queues
 *
 * Properties:
 * - Lexicographically sortable (prefix sorts by time)
 * - B-tree friendly (sequential inserts minimize page splits)
 * - Timestamp extractable (first N bits encode milliseconds)
 * - Random suffix for collision resistance
 *
 * Branded type prevents accidental misuse at compile time.
 *
 * @example
 * ```typescript
 * const eventId: TimeOrderedId = generator.timeOrderedId();
 * const timestamp = generator.extractTimestamp(eventId);
 * ```
 */
export type TimeOrderedId = string & { readonly __brand: 'TimeOrderedId' };

/**
 * W3C Trace Context trace ID.
 *
 * - 16 bytes (128 bits) encoded as 32 lowercase hex characters
 * - Must not be all zeros (invalid per W3C spec)
 *
 * Use for correlating spans across service boundaries in distributed tracing.
 *
 * @see https://www.w3.org/TR/trace-context/
 *
 * @example
 * ```typescript
 * const traceId: TraceId = generator.traceId();
 * // '0af7651916cd43dd8448eb211c80319c'
 * ```
 */
export type TraceId = string & { readonly __brand: 'TraceId' };

/**
 * W3C Trace Context span ID.
 *
 * - 8 bytes (64 bits) encoded as 16 lowercase hex characters
 * - Must not be all zeros (invalid per W3C spec)
 *
 * Use for identifying individual operations within a trace.
 *
 * @see https://www.w3.org/TR/trace-context/
 *
 * @example
 * ```typescript
 * const spanId: SpanId = generator.spanId();
 * // 'b7ad6b7169203331'
 * ```
 */
export type SpanId = string & { readonly __brand: 'SpanId' };

// =============================================================================
// Generator Interfaces (abstract categories)
// =============================================================================

/**
 * Generator for cryptographically random IDs.
 *
 * Random IDs have:
 * - No time component
 * - Maximum entropy per byte
 * - No ordering guarantees
 *
 * Default implementation: hex-encoded crypto.randomBytes
 * Override with: uuid.v4, nanoid, custom entropy source
 *
 * @example
 * ```typescript
 * // Default implementation
 * const gen = createRandomIdGenerator();
 * const id = gen.randomId();
 *
 * // Inject uuid.v4
 * const gen = createRandomIdGenerator({
 *   generate: () => uuid.v4().replace(/-/g, '')
 * });
 * ```
 */
export interface RandomIdGenerator {
  /**
   * Generate a new cryptographically random ID.
   *
   * @returns A random identifier string
   */
  randomId(): RandomId;
}

/**
 * Generator for time-ordered IDs.
 *
 * Time-ordered IDs have:
 * - Timestamp prefix (sortable)
 * - Random suffix (collision resistance)
 * - Monotonicity within process (optional, depends on implementation)
 *
 * Default implementation: 48-bit timestamp + 80-bit random in Crockford Base32
 * Override with: UUIDv7, ULID, KSUID, Snowflake
 *
 * @example
 * ```typescript
 * // Default implementation
 * const gen = createTimeOrderedIdGenerator({ clock });
 * const id = gen.timeOrderedId();
 * const ts = gen.extractTimestamp(id);
 *
 * // Inject ULID
 * const gen = createTimeOrderedIdGenerator({ clock }, {
 *   generate: (ts) => ulid(ts),
 *   extractTimestamp: (id) => decodeTime(id)
 * });
 * ```
 */
export interface TimeOrderedIdGenerator {
  /**
   * Generate a new time-ordered ID using the current wall clock time.
   *
   * @returns A time-ordered identifier with embedded timestamp
   */
  timeOrderedId(): TimeOrderedId;

  /**
   * Extract the timestamp from a time-ordered ID.
   *
   * @param id - A time-ordered ID generated by this generator
   * @returns Milliseconds since Unix epoch, or undefined if extraction fails
   */
  extractTimestamp(id: TimeOrderedId): number | undefined;
}

/**
 * Generator for W3C Trace Context compliant IDs.
 *
 * This is a FIXED FORMAT - not injectable.
 * Required for OpenTelemetry interoperability.
 *
 * @see https://www.w3.org/TR/trace-context/
 *
 * @example
 * ```typescript
 * const gen = createTraceIdGenerator();
 * const traceId = gen.traceId(); // 32 hex chars
 * const spanId = gen.spanId();   // 16 hex chars
 * ```
 */
export interface TraceIdGenerator {
  /**
   * Generate a new trace ID.
   *
   * Returns 32 lowercase hex characters (128 bits of entropy).
   * Guaranteed to be non-zero (valid per W3C Trace Context).
   *
   * Use this to correlate spans across service boundaries within a single trace.
   */
  traceId(): TraceId;

  /**
   * Generate a new span ID.
   *
   * Returns 16 lowercase hex characters (64 bits of entropy).
   * Guaranteed to be non-zero (valid per W3C Trace Context).
   *
   * Use this to identify individual operations within a trace.
   */
  spanId(): SpanId;
}

/**
 * Unified ID generator combining all ID categories.
 *
 * Use this when an application needs multiple ID types.
 * Each category can be configured independently.
 *
 * @example
 * ```typescript
 * const ids = createIdGenerator({ clock });
 *
 * ids.randomId();      // Session tokens
 * ids.timeOrderedId(); // Database primary keys
 * ids.traceId();       // Distributed tracing
 * ids.spanId();        // Span identification
 * ```
 */
export interface IdGenerator extends RandomIdGenerator, TimeOrderedIdGenerator, TraceIdGenerator {}

// =============================================================================
// Configuration Types (for port injection)
// =============================================================================

/**
 * Output encoding format for random IDs.
 */
export type RandomIdEncoding = 'hex' | 'base64' | 'base64url';

/**
 * Configuration for random ID generation.
 */
export interface RandomIdConfig {
  /**
   * Size in bytes for the random ID.
   * @default 16 (produces 32 hex characters)
   */
  readonly sizeBytes?: number;

  /**
   * Output encoding format.
   * @default 'hex'
   */
  readonly encoding?: RandomIdEncoding;
}

/**
 * Output encoding format for time-ordered IDs.
 */
export type TimeOrderedIdEncoding = 'hex' | 'base32' | 'base64url';

/**
 * Configuration for time-ordered ID generation.
 */
export interface TimeOrderedIdConfig {
  /**
   * Size in bytes for the random suffix.
   * @default 10 (80 bits of randomness)
   */
  readonly randomSuffixBytes?: number;

  /**
   * Output encoding format.
   * @default 'base32' (Crockford, lexicographically sortable)
   */
  readonly encoding?: TimeOrderedIdEncoding;
}
